### ISSUE TITLE
你好，在W2V下执行运行to_pickle.py可以得到文件W2V.pickle时          python3 to_pickle.py 报错

### ISSUE THREAD

**Issue by zuole** [nocoolsandwich/iamQA#5]
Traceback (most recent call last):
  File "to_pickle.py", line 4, in <module>
    W2V = gensim.models.KeyedVectors.load_word2vec_format(model_pt_path,binary = False,unicode_errors='ignore')
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/keyedvectors.py", line 1438, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/utils_any2vec.py", line 172, in _load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/gensim/utils.py", line 355, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 12: invalid start byte

尝试忽略错误，依然报错
# -*- coding: utf-8 -*-
import gensim,pickle
model_pt_path = r'sgns.merge.word'
W2V = gensim.models.KeyedVectors.load_word2vec_format(model_pt_path,binary = False,unicode_errors='ignore')
#W2V = gensim.models.Word2Vec.load(model_pt_path)
with open(r'W2V.pickle','wb') as f:
    pickle.dump(W2V,f)

请问如何解决呢？
库的版本和requirement.txt基本上完全一样

**Comment by nocoolsandwich** [comment]
看起来是编码问题，你看看这个api
![image](https://user-images.githubusercontent.com/25381569/106441389-f3aca180-64b4-11eb-8f91-4888ecccc5eb.png)
