### ISSUE TITLE
您好，可以启动服务 但是无法进行预测 [INFO ] Thread-0 org.pytorch.serve.wlm.ModelManager - Model W2V unregistered.

### ISSUE THREAD

**Issue by zuole** [nocoolsandwich/iamQA#6]
您好，想问一下出现下面的问题如何解决呢？
环境：
Linux gpu 
Successfully installed torch-1.7.1+cu101 torchaudio-0.7.2 torchtext-0.8.1 torchvision-0.8.2+cu101
其他基本上都是按照requirement里面安装的
报错日志：
2021-02-06 11:24:43,604 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model W2V
2021-02-06 11:24:43,605 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model W2V
2021-02-06 11:24:43,605 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model W2V loaded.
2021-02-06 11:24:43,605 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: W2V, count: 1
2021-02-06 11:24:43,611 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2021-02-06 11:24:43,639 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:9080
2021-02-06 11:24:43,640 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2021-02-06 11:24:43,642 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:9081
2021-02-06 11:24:43,642 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2021-02-06 11:24:43,646 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://0.0.0.0:9082
2021-02-06 11:24:43,832 [INFO ] W-9002-W2V_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9002
2021-02-06 11:24:43,833 [INFO ] W-9002-W2V_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]1548
2021-02-06 11:24:43,834 [INFO ] W-9002-W2V_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2021-02-06 11:24:43,834 [DEBUG] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-W2V_1.0 State change null -> WORKER_STARTED
2021-02-06 11:24:43,834 [INFO ] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9002
2021-02-06 11:24:43,834 [INFO ] W-9002-W2V_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.9
2021-02-06 11:24:43,839 [INFO ] W-9002-W2V_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9002.
Model server started.
**2021-02-06 11:24:44,414 [ERROR] Thread-1 org.pytorch.serve.metrics.MetricCollector - Traceback (most recent call last):
  File "ts/metrics/metric_collector.py", line 10, in <module>
    from ts.metrics import system_metrics
  File "/usr/local/lib/python3.6/dist-packages/ts/__init__.py", line 10, in <module>
    from . import version
  File "/usr/local/lib/python3.6/dist-packages/ts/version.py", line 7, in <module>
    version_path = os.path.join(Path(__file__).resolve().parent, 'version.txt')
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not PosixPath**

**2021-02-06 11:26:49,524 [INFO ] Thread-0 org.pytorch.serve.wlm.ModelManager - Model NER unregistered.**
2021-02-06 11:26:49,524 [INFO ] Thread-0 org.pytorch.serve.ModelServer - Unregistering model W2V version 1.0
2021-02-06 11:26:49,524 [DEBUG] Thread-0 org.pytorch.serve.wlm.ModelVersionedRefs - Removed model: W2V version: 1.0
2021-02-06 11:26:49,525 [DEBUG] Thread-0 org.pytorch.serve.wlm.WorkerThread - W-9002-W2V_1.0 State change WORKER_STARTED -> WORKER_SCALED_DOWN
2021-02-06 11:26:49,525 [WARN ] Thread-0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-W2V_1.0-stderr
2021-02-06 11:26:49,525 [WARN ] Thread-0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-W2V_1.0-stdout
2021-02-06 11:26:49,525 [DEBUG] Thread-0 org.pytorch.serve.job.Job - Waiting time ns: 0, Inference time ns: 94509988
2021-02-06 11:26:49,525 [DEBUG] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_SCALED_DOWN
2021-02-06 11:26:49,525 [INFO ] epollEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_SCALED_DOWN
2021-02-06 11:26:49,526 [DEBUG] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerThread - Shutting down the thread .. Scaling down.
2021-02-06 11:26:49,527 [WARN ] W-9002-W2V_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: W2V, error: Worker died.
2021-02-06 11:26:49,527 [DEBUG] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-W2V_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2021-02-06 11:26:49,527 [WARN ] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-W2V_1.0-stderr
2021-02-06 11:26:49,528 [WARN ] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-W2V_1.0-stdout
2021-02-06 11:26:49,528 [DEBUG] W-9002-W2V_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
2021-02-06 11:26:49,531 [INFO ] W-9002-W2V_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-W2V_1.0-stderr
2021-02-06 11:26:49,531 [INFO ] W-9002-W2V_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-W2V_1.0-stdout
**2021-02-06 11:26:49,597 [INFO ] Thread-0 org.pytorch.serve.wlm.ModelManager - Model W2V unregistered.**

**Comment by nocoolsandwich** [comment]
看起来是torchserve出了问题

`
File "ts/metrics/metric_collector.py", line 10, in
from ts.metrics import system_metrics
File "/usr/local/lib/python3.6/dist-packages/ts/init.py", line 10, in
from . import version
File "/usr/local/lib/python3.6/dist-packages/ts/version.py", line 7, in
version_path = os.path.join(Path(file).resolve().parent, 'version.txt')
File "/usr/lib/python3.6/posixpath.py", line 80, in join
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not PosixPath
`
试试torchserve==0.03
